version: "0.1"

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: gofemart
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"

  go:
    container_name: gofemart
    build:
      context: .
      dockerfile: ./deployments/docker/go/Dockerfile
    ports:
      - "8645:8080"
    environment:
      - DATABASE_URI=postgresql://postgres:example@db/gofemart
    depends_on:
      - db

